function showSentence() {
    const numberInput = document.getElementById('numberInput').value;
    const sentences = [
      "I",
      "You",
      "You",
      "He",
      "She",
      "It",
      "We",
      "They",
      "Boy",
      "Boys",
      "What",
      "What time",
      "How",
      "How long",
      "How often",
      "When",
      "Where",
      "Why",
      "Withwhom",
      "Who",
      "I can play.",
      "I can not play.",
      "Can I play?",
      "Can I not play?",
      "What can I play?",
      "What time can I play?",
      "How can  I play?",
      "How long can I play?",
      "How often can I play?",
      "When can I plya?",
      "Where can I play?",
      "Why can I play",
      "With whom can I play?",
      "Who can play?",
      "I am a teacher?",
      "I was a teacher.",
      "I shall be a teacher.",
      "I have a pen.",
      "I had a pen.",
      "I shall have a pen.",
      "I play.",
      "I played.",
      "I shall play.",
      "I am playing.",
      "I was playing.",
      "I shall be playing.",
      "I have played.",
      "I had played.",
      "I shall have played.",
      "I have been playing.",
      "I had been playing.",
      "I shall have been playing.",
      "I can play.",
      "I could play.",
      "I may play.",
      "I might play.",
      "I must play.",
      "I should play.",
      "I would play.",
      "I ought to play.",
      "I can have played.",
      "I could have played.",
      "I may have played.",
      "I might have played.",
      "I must have played.",
      "I should have played.",
      "I would have played.",
      "I ought to have played.",
      "I have to play.",
      "I had to play.",
      "I shall have to play.",
      "I am going to play.",
      "I am about to play.",
      "I am likely to play.",
      "I am able to play.",
      "I am asked.",
      "I was asked.",
      "I shall be asked.",
      "I am being asked.",
      "I was being asked.",
      "No passive voice", // Placeholder for sentence 441
      "I been asked.", // Corrected typo from the original input ("I" was changed to "I've")
      "I had been asked.",
      "I shall have been asked.",
      "No passive voice", // Placeholder for sentence 445
      "No passive voice", // Placeholder for sentence 446
      "No passive voice", // Placeholder for sentence 447
      "I can be asked.",
      "I could be asked.",
      "I may be asked.",
      "I might be asked.",
      "I must be asked.",
      "I should be asked.",
      "I would be asked.",
      "I ought to be asked.",
      "I can have been asked.",
      "I could have been asked.",
      "I may have been asked.",
      "I might have been asked.",
      "I must have been asked.",
      "I should have been asked.",
      "I would have been asked.",
      "I ought to have been asked.",
      "I have to be asked.",
      "I had to be asked.",
      "I shall have to be asked.",
      "I am going to be asked.",
      "I am about to be asked.",
      "I am likely to be asked.",
      "I am able to be asked.",
      "I am a teacher.",
      "I was a teacher.",
      "I shall be a teacher.",
      "I am being a teacher.",
      "I was being a teacher.",
      "I shall be being a teacher.",
      "I have been a teacher.",
      "I had been a teacher.",
      "I shall have been a teacher.",
      "I have been being a teacher.",
      "I had been being a teacher.",
      "I shall have been being a teacher.",
      "I can be a teacher.",
      "I could be a teacher.",
      "I may be a teacher.",
      "I might be a teacher.",
      "I must be a teacher.",
      "I should be a teacher.",
      "I would be a teacher.",
      "I ought to be a teacher.",
      "I can have been a teacher.",
      "I could have been a teacher.",
      "I may have been a teacher.",
      "I might have been a teacher.",
      "I must have been a teacher.",
      "I should have been a teacher.",
      "I would have been a teacher.",
      "I ought to have been a teacher.",
      "I have to be a teacher.",
      "I had to be a teacher.",
      "I shall have to be a teacher.",
      "I am going to be a teacher.",
      "I am about to be a teacher.",
      "I am likely to be a teacher.",
      "I am able to be a teacher.",
      "I have a pen.",
      "I had a pen.",
      "I shall have a pen.",
      "I am having a pen.",
      "I was having a pen.",
      "I shall be having a pen.",
      "I have had a pen.",
      "I had had a pen.",
      "I shall have had a pen.",
      "I have been having a pen.",
      "I had been having a pen.",
      "I shall have been having a pen.",
      "I can have a pen.",
      "I could have a pen.",
      "I may have a pen.",
      "I might have a pen.",
      "I must have a pen.",
      "I should have a pen.",
      "I would have a pen.",
      "I ought to have a pen.",
      "I can have had a pen.",
      "I could have had a pen.",
      "I may have had a pen.",
      "I might have had a pen.",
      "I must have had a pen.",
      "I should have had a pen.",
      "I would have had a pen.",
      "I ought to have had a pen.",
      "I have to have a pen.",
      "I had to have a pen.",
      "I shall have to have a pen.",
      "I am going to have a pen.",
      "I am about to have a pen.",
      "I am likely to have a pen.",
      "I am able to have a pen.",
      "I want to eat.",
      "I dare to eat.",
      "I fear to eat.",
      "I need to eat.",
      "I like to eat.",
      "I manage to eat.",
      "I refuse to eat.",
      "I permit to eat.",
      "I expect to eat.",
      "I know how to eat.",
      "I stop writing.",
      "I finish writing.",
      "I delay writing.",
      "I postpone writing.",
      "I avoid writing.",
      "I enjoy writing.",
      "I practice writing.",
      "I deny writing.",
      "I involve writing.",
      "I mind writing."
    ];
  
    if (numberInput >= 1 && numberInput <= 200) {
      const sentence = sentences[numberInput - 1];
      document.getElementById('result').textContent = sentence;
    } else {
      document.getElementById('result').textContent = 'Please enter a number between 1 and 200.';
    }
  }
  